### ISSUE TITLE
Getting Digest deprecation warning

### ISSUE THREAD

**Issue by cgswong** [mheffner/awsam#30]
I'm getting the warning `Digest::Digest is deprecated; use Digest` on both installation and when the profile script `source $HOME/.awsam/bash.rc` is run. Looks like this may be due to how the AWS libraries are being called. Looks like PR #29 may resolve this issue.

**Comment by mheffner** [comment]
@cgswong Yes, PR #29 should resolve this issue. I'd like to get some more testing on it, so will probably merge/ship it sometime next week.

**Comment by mheffner** [comment]
Fixed in 0.1.0
