### ISSUE TITLE
`aem use` fails when noclobber is set

### ISSUE THREAD

**Issue by ggerrietts** [mheffner/awsam#31]
https://github.com/mheffner/awsam/blob/master/bashrc/rc.scr#L316 uses `>` ouput redirection which will fail when noclobber is set; `>|` is safer I think?

**Comment by mheffner** [comment]
@ggerrietts yeah, actually I think just switching it to `>>` would work, since we've already created the file.

**Comment by mheffner** [comment]
Nope, we reuse the file so it has to be `>|`.
